Models/ErrorViewModel.cs
namespace TMC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/TMCDB.cs
using Microsoft.EntityFrameworkCore;

namespace TMC.Models
{
    public class TMCDB:DbContext
    {
        public DbSet<mytasks> Mytasks { get; set; }
        public DbSet<myprojects> Myprojects { get; set; }
        public DbSet<myteammember> Myteammembers { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=TMCDB;Persist Security Info=True;User ID=sa;Password=FIATS@2024;Trust Server Certificate=True");
            base.OnConfiguring(optionsBuilder);
        }
    }
}

Models/myprojects.cs
using System.ComponentModel.DataAnnotations;

namespace TMC.Models
{
    public class myprojects
    {
        [Key]
        public int Id { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(100)]
        public string Description { get; set; }
        public DateTime Startdate { get; set; }
        public DateTime Enddate { get; set; }
        /////////////////////////////////////////////////
        public List<mytasks> Mytasks { get; set; }
        /////////////////////////////////////////////////
    }
}

Models/mytasks.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace TMC.Models
{
    public class mytasks
    {
        [Key]
        public int Id { get; set; }
        [StringLength(100)]
        public string Title/*Name*/ { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
        [StringLength(50)]
        public string Propirty { get; set; }
        public DateTime Deadline { get; set; }
        /////////////////////////////////////////////////
        [ForeignKey("ProjectID")]
        public int projectID { get; set; }
        [ForeignKey("TeamMemberID")]
        public int teamMemberID { get; set; }
        /////////////////////////////////////////////////
        public myteammember TeamMemberID { get; set; }
        public myprojects ProjectID { get; set; }
    }
}

Models/myteammember.cs
using System.ComponentModel.DataAnnotations;

namespace TMC.Models
{
    public class myteammember
    {
        public int Id { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        [StringLength(50)]
        public string Role { get; set; }

        public List<mytasks> Mytasks { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TMC.Models;

namespace TMC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MYPROJECTSController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TMC.Models;

namespace TMC.Controllers
{
    public class MYPROJECTSController : Controller
    {
        TMCDB db = new TMCDB();
        mytasks Mytasks;
        public IActionResult Index()
        {
            var list = db.Myprojects.ToList();
            return View(list);
        }
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(myprojects myprojects)
        {
            db.Myprojects.Add(myprojects);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }


        public ActionResult Update(int id)
        {
            var updated = db.Myprojects.FirstOrDefault(x => x.Id == id);
            if (updated != null)
            {
                return View(updated);
            }
            else
            {
                return NotFound();
            }
        }
        [HttpPost]
        public ActionResult Update(myprojects myprojects)
        {
            db.Myprojects.Update(myprojects);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var Deleted = db.Myprojects.FirstOrDefault(x => x.Id == id);
            if (Deleted != null)
            {
                db.Myprojects.Remove(Deleted);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }
    }
}

Controllers/MYTASKSController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TMC.Models;

namespace TMC.Controllers
{
    public class MYTASKSController : Controller
    {
        TMCDB db = new TMCDB();
        myteammember Myteammember;
        myprojects myprojects;
        public IActionResult Index()
        {
            var list = db.Mytasks.ToList();
            return View(list);
        }

        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(mytasks mytasks)
        {
            db.Mytasks.Add(mytasks);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }


        public ActionResult Update(int id) 
        {
           var updated = db.Mytasks.FirstOrDefault(x => x.Id == id);
            if (updated != null) 
            {
                return View(updated);
            }
            else
            {
                return NotFound();
            }
        }
        [HttpPost]
        public ActionResult Update(mytasks mytasks)
        {
            db.Mytasks.Update(mytasks); 
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id) 
        {
            var updated = db.Mytasks.FirstOrDefault(x => x.Id == id);
            if (updated != null)
            {
               db.Mytasks.Remove(updated);
               db.SaveChanges();
               return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            } 
        }
    }
}

Controllers/MYTEAMMEMBERController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TMC.Models;

namespace TMC.Controllers
{
    public class MYTEAMMEMBERController : Controller
    {
        TMCDB db = new TMCDB();
        public IActionResult Details()
        {
            var list = db.Myteammembers.ToList();
            return View(list);
        }
        public ActionResult Update(int id)
        {
            var updated = db.Myteammembers.FirstOrDefault(x => x.Id == id);
            if (updated != null)
            {
                return View(updated);
            }
            else
            {
                return NotFound();
            }
        }
        [HttpPost]
        public ActionResult Update(myteammember myteammember)
        {
            db.Myteammembers.Update(myteammember);
            db.SaveChanges();
            return RedirectToAction(nameof(Details));
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/MYPROJECTS/Add.cshtml
@model myprojects
@{
}
<form class="form-control mb-3" asp-action="Add" asp-controller="MYPROJECTS">
    <div class="form-control mb-3">
        <label asp-for="Name">Project Name</label>
        <input asp-for="Name">
    </div>
    <div class="form-control mb-3">
        <label asp-for="Startdate">Project's Startdate</label>
        <input asp-for="Startdate">
    </div>
    <div class="form-control mb-3">
        <label asp-for="Enddate">Project's Enddate</label>
        <input asp-for="Enddate">
    </div>
    </div><div class="form-control mb-3">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>


Views/MYPROJECTS/Index.cshtml
@model IEnumerable<myprojects>
@{
}
<h1>Project Management</h1>
<hr />

<a class="btn btn-primary" asp-action="Add" asp-controller="MYPROJECTS">Add New Project</a>
</p>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Project Name</th>
            <th>Project Description</th>
            <th>Project Startdate</th>
            <th>Project Enddate</th>
            <th>Project's Tasks</th>          
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.Description</td>
                <td>@item.Startdate</td>
                <td>@item.Enddate</td>
                <td>@item.Mytasks.</td>
             
                <td>
                    <a class="btn btn-primary" asp-controller="MYPROJECTS" asp-action="Update" asp-route-id="@item.Id">Update</a>
                    <a class="btn btn-danger" asp-controller="MYPROJECTS" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/MYPROJECTS/Update.cshtml
@model myprojects
@{
}
<form class="form-control mb-3" asp-action="Add" asp-controller="MYPROJECTS">
    <div class="form-control mb-3">
        <label asp-for="Name">Project Name</label>
        <input asp-for="Name">
    </div>
    <div class="form-control mb-3">
        <label asp-for="Startdate">Project's Startdate</label>
        <input asp-for="Startdate">
    </div>
    <div class="form-control mb-3">
        <label asp-for="Enddate">Project's Enddate</label>
        <input asp-for="Enddate">
    </div>
    </div><div class="form-control mb-3">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

Views/MYTASKS/Index.cshtml
@model IEnumerable< mytasks>
@{
}
<h1>Tasks</h1>
<hr />

<a class="btn btn-primary" asp-action="Add" asp-controller="MYTASKS">Add New Task</a>
</p>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Task Name</th>
            <th>Task Description</th>
            <th>Task Status</th>
            <th>Task Propirty</th>
            <th>Task Deadline</th>
            <th>Task Project</th>
            <th>Task Team Member</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Title</td>
                <td>@item.Description</td>
                <td>@item.Status</td>
                <td>@item.Propirty</td>
                <td>@item.Deadline</td>
                <td>@item.projectID</td>
                <td><a asp-action="DEtails" asp-controller="MYTEAMMEMBER">
                    @item.teamMemberID
					</a>
				</td>
                <td>
                <a class="btn btn-primary" asp-action="Update" asp-route-id="@item.Id">Update</a>
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>


Views/MYTASKS/Update.cshtml
@model mytasks
@{
}
<form class="form-control mb-3" asp-action="Update" asp-controller="MYTASKS">
    <div class="form-control mb-3">
        <label asp-for="Title">Task Name</label>
        <input asp-for="Title">
    </div><div class="form-control mb-3">
        <label asp-for="Description">Task Description</label>
        <input asp-for="Description">
    </div>
    <div class="form-control mb-3">
        <label asp-for="Status">Task Status</label>
        <input asp-for="Status">
    </div><div class="form-control mb-3">
        <label asp-for="Propirty">Task Propirty</label>
        <input asp-for="Propirty">
    </div>
    <div class="form-control mb-3">
        <label asp-for="Deadline">Task Deadline</label>
        <input asp-for="Deadline">
    </div><div class="form-control mb-3">
        <label asp-for="projectID">Task projectID</label>
        <input asp-for="projectID">
    </div>
    <div class="form-control mb-3">
        <label asp-for="teamMemberID">Task teamMemberID</label>
        <input asp-for="teamMemberID">
    </div><div class="form-control mb-3">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

Views/MYTASKS/add.cshtml
@model mytasks
@{
}
<form class="form-control mb-3" asp-action="Add" asp-controller="MYTASKS">
    <div class="form-control mb-3">
        <label asp-for="Title">Task Name</label>
        <input asp-for="Title">
    </div><div class="form-control mb-3">
        <label asp-for="Description">Task Description</label>
		<input asp-for="Description">
	</div>
    <div class="form-control mb-3">
        <label asp-for="Status">Task Status</label>
        <input asp-for="Status">
    </div><div class="form-control mb-3">
        <label asp-for="Propirty">Task Propirty</label>
		<input asp-for="Propirty">
	</div>
    <div class="form-control mb-3">
        <label asp-for="Deadline">Task Deadline</label>
        <input asp-for="Deadline">
    </div><div class="form-control mb-3">
		<label asp-for="projectID">Task projectID</label>
		<input asp-for="projectID">
	</div>
    <div class="form-control mb-3">
        <label asp-for="teamMemberID">Task teamMemberID</label>
        <input asp-for="teamMemberID">
    </div><div class="form-control mb-3">
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>
</form>

Views/MYTEAMMEMBER/Details.cshtml
@model IEnumerable< myteammember>
@{
}
<h1>Member Management</h1>
<hr />


<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Member Name</th>
            <th>Member Email</th>
            <th>Member Role</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
           {
            <tr>
                <td>@item.Name</td>
                <td>@item.Email</td>
                <td>@item.Role</td>
                <td>
                    <a class="btn btn-primary" asp-action="Update" asp-route-id="@item.Id">Update</a>                   
                </td>
            </tr>
           }
    </tbody>
</table>

Views/MYTEAMMEMBER/Update.cshtml

@model myteammember
@{
}
<form class="form-control mb-3" asp-action="Update" asp-controller="MYTEAMMEMBER">
    <div class="form-control mb-3">
        <label asp-for="Name">Member Name</label>
        <input asp-for="Name">
    </div>
    <div class="form-control mb-3">
        <label asp-for="Email">Member Email</label>
        <input asp-for="Email">
    </div>
    <div class="form-control mb-3">
        <label asp-for="Role">Member Role</label>
        <input asp-for="Role">
    </div>
    <div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TMC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TMC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TMC:Task Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-right">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MYTASKS" asp-action="Index">Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MYTEAMMEMBER" asp-action="Details">Members</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MYPROJECTS" asp-action="Index">Projects</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TMC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>